ufw_rules:
  - { port: 22, rule: allow, comment: 'Allow SSH' }
  - { port: 12101, rule: allow, comment: 'Allow Rhasspy' }
  - { port: 12183, rule: allow, comment: 'Allow Rhasspy-MQTT' }
  - { port: 5000, rule: allow, comment: 'Allow radio_api' }
  - { port: 1880, rule: allow, comment: 'Allow node-red' }
