version: "3"

services:
  rhasspy:
      container_name: rhasspy
      image: "rhasspy/rhasspy:latest"
      ports:
          - "12101:12101"
      volumes:
          - "./profiles:/profiles"
      devices:
          - "/dev/snd:/dev/snd"
      command: --user-profiles /profiles --profile de
      restart: unless-stopped
