---
- hosts: assistants
  remote_user: pi
  become: true
  pre_tasks:
    - name: Load firewall configuration
      include_vars: ufw_configuration.yml
    - name: Install core packages
      apt:
        name:
          - git
          - htop
          - screen
          - vim
          - libffi-dev
          - libssl-dev
          - dnsutils
    - name: Avoid kernel upgrades (needed for voicecard driver)
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - raspberrypi-kernel
        - raspberrypi-kernel-headers



  post_tasks:
    - name: Set swappiness
      sysctl:
        name: vm.swappiness
        value: '0'
        sysctl_file: /etc/sysctl.d/99-local.conf
        reload: yes
    - name: Clone seeed-voicecard driver
      git:
        repo: https://github.com/respeaker/seeed-voicecard.git
        dest: /home/pi/seeed-voicecard
        update: no
      become: false
    - name: Remove broken Python module
      pip:
        name: backports.ssl_match_hostname
        state: absent
    - name: Install working Python module
      apt:
        name:
          - python-backports.ssl-match-hostname
    - name: Install required PIP modules
      pip:
        name:
          - docker
          - pixel_ring
          - gpiozero
    - name: Download Docker images
      docker_image:
        name: "{{ item }}"
        source: pull
      with_items:
        - stdevel/radio_api:latest
        - synesthesiam/rhasspy-server:latest
    - name: Create Docker networks
      docker_network:
        name: "{{ item }}"
      with_items:
        - rhasspy_default
        - radio_api_default
    - name: Create configuration directories
      file:
        path: "{{ item }}"
        owner: pi
        group: pi
        mode: '0750'
        state: directory
      with_items:
        - /home/pi/rhasspy
        - /home/pi/radio_api
    - name: Stage Rhasspy configuration
      template:
        src: rhasspy-docker-compose.yml
        dest: /home/pi/rhasspy/docker-compose.yml
        owner: pi
        group: pi
        mode: '0644'
    - name: Stage radio_api configuration
      template:
        src: radio_api-docker-compose.yml
        dest: /home/pi/radio_api/docker-compose.yml
        owner: pi
        group: pi
        mode: '0644'



  roles:
    - role: nickjj.docker
      docker__apt_repository: "deb [arch=armhf] https://download.docker.com/linux/debian buster stable"
    - role: weareinteractive.ufw
      ufw_reset: true
